/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class'],
  content: [
    './src/renderer/**/*.{ts,tsx,html}',
    './src/renderer/index.html',
  ],
  theme: {
    extend: {
      colors: {
        // SyncNode Design Tokens
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        surface: {
          0: 'hsl(var(--surface-0))',
          1: 'hsl(var(--surface-1))',
          2: 'hsl(var(--surface-2))',
          3: 'hsl(var(--surface-3))',
          4: 'hsl(var(--surface-4))',
        },
        border: 'hsl(var(--border))',
        'border-subtle': 'hsl(var(--border-subtle))',
        'border-strong': 'hsl(var(--border-strong))',
        text: {
          primary: 'hsl(var(--text-primary))',
          secondary: 'hsl(var(--text-secondary))',
          tertiary: 'hsl(var(--text-tertiary))',
          disabled: 'hsl(var(--text-disabled))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        success: 'hsl(var(--success))',
        warning: 'hsl(var(--warning))',
        danger: 'hsl(var(--danger))',
        info: 'hsl(var(--info))',
        // shadcn/ui compat
        card: { DEFAULT: 'hsl(var(--surface-1))', foreground: 'hsl(var(--foreground))' },
        popover: { DEFAULT: 'hsl(var(--surface-2))', foreground: 'hsl(var(--foreground))' },
        primary: { DEFAULT: 'hsl(var(--accent))', foreground: 'hsl(var(--accent-foreground))' },
        secondary: { DEFAULT: 'hsl(var(--surface-3))', foreground: 'hsl(var(--text-secondary))' },
        muted: { DEFAULT: 'hsl(var(--surface-2))', foreground: 'hsl(var(--text-tertiary))' },
        destructive: { DEFAULT: 'hsl(var(--danger))', foreground: 'hsl(0 0% 95%)' },
        input: 'hsl(var(--border))',
        ring: 'hsl(var(--focus))',
      },
      borderRadius: {
        micro: '2px',
        sm: '4px',
        DEFAULT: '6px',
        md: '6px',
        lg: '8px',
        xl: '10px',
        '2xl': '12px',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'Consolas', 'monospace'],
      },
      fontSize: {
        'micro': ['10px', { lineHeight: '14px' }],
        'meta': ['11px', { lineHeight: '16px' }],
        'compact': ['12px', { lineHeight: '16px' }],
        'body': ['13px', { lineHeight: '20px' }],
        'ui': ['14px', { lineHeight: '20px' }],
        'section': ['16px', { lineHeight: '22px' }],
        'panel': ['18px', { lineHeight: '24px' }],
        'screen': ['20px', { lineHeight: '28px' }],
        'title': ['24px', { lineHeight: '30px' }],
        'hero': ['36px', { lineHeight: '42px' }],
      },
      spacing: {
        '0.5': '2px',
        '1': '4px',
        '1.5': '6px',
        '2': '8px',
        '3': '12px',
        '4': '16px',
        '5': '20px',
        '6': '24px',
        '8': '32px',
        '10': '40px',
      },
      keyframes: {
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'slide-in-from-left': {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(0)' },
        },
        'slide-in-from-right': {
          '0%': { transform: 'translateX(100%)' },
          '100%': { transform: 'translateX(0)' },
        },
        'slide-in-from-bottom': {
          '0%': { transform: 'translateY(8px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        'shimmer': {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        'pulse-dot': {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.3' },
        },
      },
      animation: {
        'fade-in': 'fade-in 0.2s ease-out',
        'slide-in-left': 'slide-in-from-left 0.2s ease-out',
        'slide-in-right': 'slide-in-from-right 0.2s ease-out',
        'slide-in-bottom': 'slide-in-from-bottom 0.15s ease-out',
        'shimmer': 'shimmer 2s linear infinite',
        'pulse-dot': 'pulse-dot 2s ease-in-out infinite',
      },
      opacity: {
        '2': '0.02',
        '3': '0.03',
        '4': '0.04',
        '8': '0.08',
        '12': '0.12',
        '15': '0.15',
        '35': '0.35',
        '45': '0.45',
        '65': '0.65',
        '85': '0.85',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
}
